import { Inter } from 'next/font/google';
import './globals.css';
import { Header } from '@/modules/Header';
import { Footer } from '@/modules/Footer';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
	return (
		<html lang='uk'>
			<body>
				<Header />
				<main className=''>{children}</main>
				<Footer />
			</body>
		</html>
	);
}
